server:
    port: 8080
security:
    basic.enabled: true
spring:
    profiles:
        active: @profile@
    application.name: nutcase
    jpa:
        open-in-view: false
        show_sql: false
    hibernate:
        ddl-auto: update
        naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
# Spring boot admin does not work with spring boot 1.3 if logfile endpoint is enabled
# https://github.com/codecentric/spring-boot-admin/issues/117
endpoints:
    logfile:
        enabled: false
        
nc:
    mail:
        from: noreply@nutcase.com

---

spring:
    profiles: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        platform: h2
        driver-class-name: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:nutcase;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
    jpa:
        database: H2
#        database-platform: org.theronin.nutcase.config.persistence.FixedH2Dialect
        show_sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false

# ===================================================================
# Nutcase specific properties
# ===================================================================

nc:
    security:
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: mySecretRememberMe

---

spring:
    profiles: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
logging:
    file: nutcase.log
    
nc:
    security:
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: mySecretRememberMe